# Generated by Django 4.1.3 on 2022-11-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_point_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='studio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='studios.studio'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='images', to='studios.amenity'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='studios.image'),
        ),
    ]
