# Generated by Django 4.1.3 on 2022-11-18 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_alter_studio_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='point',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='studios.studio'),
        ),
    ]
