# Generated by Django 4.1.3 on 2022-11-18 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_alter_point_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='geolocation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geolocation', to='studios.point'),
        ),
    ]
