# Generated by Django 4.1.3 on 2022-11-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_remove_studio_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='amenities',
        ),
    ]
