# Generated by Django 4.1.3 on 2022-11-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0011_amenity_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='studio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image', to='studios.studio'),
            preserve_default=False,
        ),
    ]
