# Generated by Django 4.1.3 on 2022-11-18 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0012_remove_studio_images_image_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='studios.studio'),
        ),
    ]
