# Generated by Django 4.1.3 on 2022-11-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0013_alter_image_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('recurrence_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywords', to='studios.studioclass')),
            ],
        ),
    ]
