# Generated by Django 4.1.3 on 2022-11-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0014_studioclass_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioclass',
            name='studio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='studios.studio'),
            preserve_default=False,
        ),
    ]
