# Generated by Django 4.1.3 on 2022-11-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0015_studioclass_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioclass',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studioclass',
            name='recurrence_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studioclass',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
