# Generated by Django 4.1.3 on 2022-11-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0022_classbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooking',
            name='studio_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='studios.studioclass'),
        ),
    ]
